### ISSUE TITLE
allow us to use sns-share for github

### ISSUE THREAD

**Issue by theonlygusti** [viosey/hexo-theme-material#166]
I'd love to be able to add a link at the bottom of the page for my github account. However, the `sns-share` option doesn't currently seem to be able to do this.

**Comment by pidupuis** [comment]
This option exists, I use it for my own blog. You have to use the `sns` option, not `sns_share`. The former corresponds to the footer links and the latter corresponds to the platform where to share your page.

**Comment by theonlygusti** [comment]
@pidupuis But it doesn't put a logo into the footer section.

I have already set my `sns.github` option.

**Comment by theonlygusti** [comment]
@pidupuis 

```yml
sns:
    email: youremail@email.com
    facebook:
    twitter:
    googleplus:
    weibo: 
    instagram: 
    tumblr: 
    github: "https://github.com/theonlygusti"
    linkedin: 
    zhihu: 
    bilibili: 
    telegram: 

```
