### ISSUE TITLE
关闭行号无法显示文章内容

### ISSUE THREAD

**Issue by YumeMichi** [viosey/hexo-theme-material#20]
并且footer部分会有神秘的乱码

**Comment by viosey** [comment]
关闭行号是什么意思？

**Comment by YumeMichi** [comment]
```
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:
```
