### ISSUE TITLE
不算子统计

### ISSUE THREAD

**Issue by w4lle** [viosey/hexo-theme-material#27]
配置

```
# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"
```
但是不显示呢？
