### ISSUE TITLE
scheme isolation didn't get button of tags, about and etc

### ISSUE THREAD

**Issue by huangjj27** [viosey/hexo-theme-material#271]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

-----------

I' m new to the hexo theme, and I checked the documents and know that there will be icon of about at the left side bar when using scheme isolation. but I failed to manage to set the icon on.

here is my setting:

```
# Sidebar Customize
sidebar:
    dropdown:
        Email Me:
            link: "#"
            icon: email
    homepage:
        use: true
        icon: home
        divider: false
    archives:
        use: true
        icon: inbox
        divider: false
    categories:
        use: true
        icon: chrome_reader_mode
        divider: false
    pages:
        About:
            link: "/about"
            icon: person
            divider: false
    article_num:
        use: false
        divider: false
    footer:
        divider: true
        theme: true
        support: false
```

but what I get is just a button of homepage:

![image](https://cloud.githubusercontent.com/assets/8068443/24834275/b7c47ef6-1d12-11e7-9c76-fc6a38b075fd.png)

Did I foget something to do?
