### ISSUE TITLE
主题文档错误,缺少启用“必应美图”的图片作为背景时,parameter的介绍.

### ISSUE THREAD

**Issue by KeJunMao** [viosey/hexo-theme-material#296]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

----
## 1
在 [Material 主题文档 -配置介绍](https://material.viosey.com/intro/) 中的:

---
### head
用于配置生成的 HTML 文件的头部信息。

* favicon: 网站的 favicon
* **high_res_favicon**: 高清 favicon
* **high_res_favicon**: iOS 主屏按钮图标
* keywords: 网站关键词
---

以上加粗部分重复,应当改为:

---
### head
用于配置生成的 HTML 文件的头部信息。

* favicon: 网站的 favicon
* high_res_favicon: 高清 favicon
* apple_touch_icon: iOS 主屏按钮图标
* keywords: 网站关键词
---

## 2

关于启用bing作为背景图片,看到config中的注释为:
```yaml
# bing available parameter:
#     new | color= | type=
#         color available value: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow
#         type available value: A (animal), C (culture), N (nature), S (space), T (travel)
```

那么,正确的例子是不是:
```yaml
background:
    #purecolor: "#F5F5F5"
    #bgimg: "/img/bg.png"
    bing:
        enable: false
        parameter:
              color=: blue
              type=: A
```
请求添加到中文文档!(英文有的样子
以上,谢谢!
