### ISSUE TITLE
Cannot GET /[object%20Object]/

### ISSUE THREAD

**Issue by lwj1994** [viosey/hexo-theme-material#305]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

在Isolation主题下进入我自定义的page时，提示'Cannot GET /[object%20Object]/'，而在默认主题没有问题。

**Comment by neoFelhz** [comment]
Please give us the demo or the raw logs.

**Comment by lwj1994** [comment]
@neoFelhz 
主题为Isolation。
_config.yml: 
```yml
sidebar:
    # dropdown:
        # Email Me: 
        #     link: "mailto: alwjlola@gmail.com"
        #     icon: email
    homepage:
        use: true
        icon: home
        divider: false
    archives:
        use: true
        icon: inbox
        divider: false
    categories:
        use: true
        icon: chrome_reader_mode
        divider: false
    pages:
        关于:
            link: "/about"
            icon: person
            divider: false
        # 标签云:
            # link: "/tags"
            # icon: label
            # divider: false
    article_num:
        use: true
        divider: false
    footer:
        divider: true
        theme: false
        support: false
        feedback: false
        material: false
```
在首页点`关于`后地址栏会显示`http://localhost:4000/[object%20Object]/`，页面显示`Cannot GET /[object%20Object]/`。我尝试输入`http://localhost:4000/about`是可以正常访问的。点击关于的时候地址不知道为啥会解析成[object%20Object]。  
  
debug 显示：

```
GET /[object%20Object] 302 0.084 ms - -
GET /[object%20Object]/ 404 0.394 ms - 149
```
关于日志我不知道在哪里看。

**Comment by Halyul** [comment]
请贴配置文件截图 直接这样看貌似并没有任何问题

**Comment by lwj1994** [comment]
```yml
# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/favicon.png"
    high_res_favicon: "/img/favicon.png"
    apple_touch_icon: "/img/favicon.png"
    keywords:

# Jump Links Settings
url:
    rss:
    daily_pic: "#"
    logo: "http://weibo.com/2846573650"


# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
# scheme: Paradox
scheme: Isolation

# UI & UX: slogan, color, effect
uiux:
    slogan: "无形装x，最为致命。"
    theme_color: "#407EE9"
    theme_sub_color: "#DF3F32"
    hyperlink_color: "#EEB405"
    button_color: "#DD1C5E"
    android_chrome_color: "#0097A7"
    nprogress_color: "#29d"
    nprogress_buffer: "800"

# JS Effect Switches
js_effect:
    fade: true
    smoothscroll: true

# Reading experience
reading:
    entry_excerpt: 80

# Thumbnail Settings
thumbnail:
    purecolor: “#407EE9“
    random_amount: 19

# Background Settings
# bing available parameter:
#     new | color= | type=
#         color available value: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow
#         type available value: A (animal), C (culture), N (nature), S (space), T (travel)
background:
    purecolor: "#FAFAFFA"
    # bgimg: "/img/bg.png"
    bing:
        enable: false
        parameter:



# Images Settings
img:
    logo: "/img/logo.png"
    avatar: "/img/avatar.png"
    daily_pic: "/img/daily_pic.png"
    sidebar_header: "/img/sidebar_header.png"
    footerico: "/img/footer/footer_ico-"
    random_thumbnail: "/img/random/material-"
    footer_image:
    #     upyun_logo:
    #         link: "https://www.upyun.com/"
    #         src: "/img/upyun_logo.svg"

# Custom Fonts
fonts: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif

# Card Elevation Level
card_elevation: 100


# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# SNS Menu
sns:
    email: alwjlola@gmail.com
    facebook: "https://www.facebook.com/venjerLu"
    twitter: "https://twitter.com/Amazeeeeeee"
    googleplus: "https://plus.google.com/u/0/112518238156441385788"
    weibo: "http://weibo.com/venjerlovesuzy"
    instagram: 
    tumblr:
    github: 
    linkedin:
    zhihu:
    bilibili:
    telegram:

# SNS Share Switch
sns_share:
    twitter: true
    facebook: true
    googleplus: true
    weibo: true
    linkedin: true
    qq: true
    telegram: true

# Sidebar Customize
sidebar:
    # dropdown:
        # Email Me: 
        #     link: "mailto: alwjlola@gmail.com"
        #     icon: email
    homepage:
        use: true
        icon: home
        divider: false
    archives:
        use: true
        icon: inbox
        divider: false
    categories:
        use: true
        icon: chrome_reader_mode
        divider: false
    pages:
        关于:
            link: "/about"
            icon: person
            divider: false
        # 标签云:
            # link: "/tags"
            # icon: label
            # divider: false
    article_num:
        use: true
        divider: false
    footer:
        divider: true
        theme: false
        support: false
        feedback: false
        material: false

# Qrcode for redirect at other device
qrcode: true

# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------

# MaterialCDN
# When you set 'use' as true, the needed css, js, font file will have a new src.
# The new src will have the base domain you configured in 'base'.
materialcdn: 
    use: 
    base: 

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: disqus
    shortname: 
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key:

# Analytics Systems
analytics:
    baidu_id:
    google_id: 

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"


```
站点配置：
```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: lu
subtitle: 
description:
author: lu
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://luwenjie.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: material

prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'default'
  line_number: true    # default false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
  type: git
  repo: 
     
```
