### ISSUE TITLE
Colors don't get applied

### ISSUE THREAD

**Issue by matteozambon89** [viosey/hexo-theme-material#360]
In my `/themes/materia/_config.yml` I've set
```
uiux:
    slogan: "Welcome to Yeeti's blog"
    theme_color: "#2196f3"
    theme_sub_color: "#16aadb"
    hyperlink_color: "#16aadb"
    button_color: "#16aadb"
    android_chrome_color: "#0189cd"
    nprogress_color: "#2fd1eb"
    nprogress_buffer: "800"
```

But the colors don't get applied.
