### ISSUE TITLE
travis-ci持续集成未成功，错误分析

### ISSUE THREAD

**Issue by MrNickLock** [viosey/hexo-theme-material#388]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

本地部署正常，换用travis-ci持续集成时报错：

```bash
Unhandled rejection TypeError: /home/travis/build/MrNickLock/MrNickLock.github.io/themes/material/layout/post.ejs:72
    70|                 <!-- Post Comments -->
    71|                 <% if(page.comment !== false) { %>
 >> 72|                     <%- partial('_partial/comment') %>
    73|                 <% } %>
    74|             </div>
    75| 


Unhandled rejection TypeError: /home/travis/build/MrNickLock/MrNickLock.github.io/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html lang="<%- config.language.substring(0,2) %>">
 >> 3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>
    6|         <!-- Single Gallery Page -->
```
以上只是众多报错中的两个典型，其他报错都是有关 partial('_partial/XXXX)的，换用默认landscape主题，一切正常。
因为十分喜爱material主题，折腾许久

.travis.yml配置如下：(如有不妥之处，还望不吝赐教，阿里嘎多！)

```yaml
language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install
  - npm i -S hexo-prism-plugin

#before_script:
  - npm install -g gulp

script:
  # - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "xxxx"
  - git config user.email "xxxxxxx@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/MrNickLock/MrNickLock.github.io.git
```
