### ISSUE TITLE
highlight not work

### ISSUE THREAD

**Issue by OhYee** [viosey/hexo-theme-material#472]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

我已经安装了prism插件，但是没有效果
站点_config设置如(另外我关了行号，他还是显示)
并且如果我不用prism用hexo自带的高亮，也是一样的效果
```
highlight:
  enable: false
  # line_number: false
  # auto_detect: false
  # tab_replace: true

prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'default'
  line_number: false    # default false
```
