### ISSUE TITLE
无法设置背景图片

### ISSUE THREAD

**Issue by LewisJin** [viosey/hexo-theme-material#49]
在
background:
    purecolor: 
   bgimg:
中我分别设置了purecolor和bgimg，背景都显示是白色，没有效果，其他人是这样的吗？还是我设置的方法不对？

**Comment by neoFelhz** [comment]
发一下你的配置看看？
我的是：
```yml
    purecolor: "#E0E0E0"
    #bgimg: "/img/bg.png"
    bing: 
        enable: false
        parameter: 
```
（一次只能选择一种，另一种要注释掉）
