### ISSUE TITLE
Relative Page's Links w/Non-Default Root Bug

### ISSUE THREAD

**Issue by twinfifty** [viosey/hexo-theme-material#504]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [X ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ X] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ X] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [X ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

When the site has non-default root, i.e.

```yaml
root: /web
```

And in the theme's _config.yaml has pages:

```yaml
    pages:
        Page 1:
            link: "/page-1"
            icon: person
            divider: false
        Page 2:
            link: "/page-2"
            icon: person
            divider: false
```

The generated links for menus are:
```
http://localhost:4000/page-1
http://localhost:4000/page-2
```

When they **should be**
```
http://localhost:4000/web/page-1
http://localhost:4000/web/page-2
```

Solution that I found is by calling the helper function _url_for_ in _side-navigation.js_ partial:

```ejs
<a href="<%= url_for(theme.sidebar.pages[i].link) %>" title="<%= i %>">
  <% if(theme.sidebar.pages[i].icon){ %>
     <i class="material-icons sidebar-material-icons"><%= theme.sidebar.pages[i].icon %></i>
       <% } %>
       <%= i %>
</a>
```

### Issue may also occur with loading other resources, e.g. font files

Since the fonts are called from css files (e.g. fontawesome.min.css), currently there is no solution to make the url dynamic. The only way to solve this (as far as I know) is to hard code it into the css file, i.e. change from `../fonts/......` to `../web/......`.

One workaround (that I currently use) is just by using a cdn, so that all fonts and css are loaded from a third-party.
