### ISSUE TITLE
日期格式没有使用 _config.yml 中的 date_format

### ISSUE THREAD

**Issue by ysc3839** [viosey/hexo-theme-material#527]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

日期格式没有使用 `_config.yml` 中的 `date_format`.
https://github.com/viosey/hexo-theme-material/blob/047837bc1081cbe7e047c935b7f905a51fe7f309/layout/_partial/Paradox-post_entry.ejs#L41
`'MMM DD, YYYY'` -> `config.date_format`

**Comment by neoFelhz** [comment]
我们为了显示效果，没有使用 `config.date_format` 。

**Comment by ysc3839** [comment]
@neoFelhz 希望给用户自定义的选项

**Comment by huangjj27** [comment]
@ysc3839 请在hexo站点配置文件中配置时间格式.

```yml 
# hexo_server/_config.yml line 51

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
```
