### ISSUE TITLE
Support Request: How to remove license in some page?

### ISSUE THREAD

**Issue by huangjj27** [viosey/hexo-theme-material#544]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

I set global config of license in the theme's config, and from the docs I know that I can override the license in the post's `front-matter`, so when I found my about page has a license like this:
![image](https://user-images.githubusercontent.com/8068443/31282648-c621ab34-aae5-11e7-91be-ba70abbb1c7e.png)

I try to disable the it's license with these setting
```yml
-----
title: 关于我
date: 2016-05-05 21:52:09
updated: 2017-10-06 22:31:05

# both Capital and normal case license have been tried!
# remain it empty but no effect
license:

# neither set the license to `false` or `null`
# license: false
# license: null
# license: ''
-----
```

Be grateful for your supportment or helpful discussion!
