### ISSUE TITLE
Valine评论系统不生效

### ISSUE THREAD

**Issue by ruibaby** [viosey/hexo-theme-material#575]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

_config.yml配置：
```yaml
comment:
    use: valine
    shortname: # duoshuo or disqus shortname
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    livere_data_uid:
    gitment_repo:   # git repo of the hexo
    gitment_owner:  # git repo's owner
    gitment_client_id:  # github app client id 
    gitment_client_secret :  # github app client secret 
    valine_leancloud_appId: KY1CgVnFfMW5T4nF1qJAgDOA-gzGzoHsz
    valine_leancloud_appKey: Q0OtvraPddSy6rqCf44zfUVg
```

在Leancloud中也已经配置好，但是hexo s和部署后，在文章底部均没有评论框，F12也没有js报错。希望能尽快答复一下，谢谢。
