### ISSUE TITLE
Markdown 代码块显示没有高亮，并且排版有问题

### ISSUE THREAD

**Issue by xiansenLiu** [viosey/hexo-theme-material#587]
![screenshot from 2017-12-23 15-56-59](https://user-images.githubusercontent.com/15999179/34318128-78f404fe-e7fa-11e7-8d66-3d72bf7f6b88.png)

**Comment by xiansenLiu** [comment]
站点配置文件
```yaml
highlight:
  enable: false
  line_number: true
  auto_detect: true
  tab_replace:
```

主题配置文件
```yaml
prettify:
    enable: false
    theme: "github-v2"

hanabi:
    enable: false
    line_number: true
    includeDefaultColors: true
    customColors: 
```

hanabi 改成 true 也是这样
