### ISSUE TITLE
使用自带prettify出现高亮问题

### ISSUE THREAD

**Issue by tetsaicn** [viosey/hexo-theme-material#601]
**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [X] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [X] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [X] support request | 请求技术支持

配置：
```YAML
prettify:
    enable: true
    theme: "github-v2"
```

行号重复显示3次，但是代码高亮正常。
渲染结果Html浏览：
<figure class="highlight html"><table><tbody><tr><td class="gutter"><pre class="prettyprint linenums prettyprinted" style="overflow: auto;"><ol class="linenums"><li class="L0"><span class="line"><span class="lit">1</span></span><br></li></ol></pre></td><td class="code"><pre class="prettyprint linenums prettyprinted" style="overflow: auto;"><ol class="linenums"><li class="L0"><span class="line"><span class="tag"><span class="tag">&lt;</span><span class="name"><span class="tag">img</span></span><span class="pln"> </span><span class="attr"><span class="atn">src</span></span><span class="pun">=</span><span class="string"><span class="atv">"原图片"</span></span><span class="pln"> </span><span class="attr"><span class="atn">onError</span></span><span class="pun">=</span><span class="string"><span class="atv">'</span><span class="kwd">this</span><span class="pun">.</span><span class="pln">src</span><span class="pun">=</span><span class="str">"备份图片"</span><span class="atv">'</span></span><span class="pln"> </span><span class="tag">/&gt;</span></span></span><br></li></ol></pre></td></tr></tbody></table></figure>

**Comment by LarryLeo** [comment]
@tetsaicn 先在配置文件里关闭hexo自带的行号显示项。

**Comment by zjy01** [comment]
同样遇到了这个问题，关闭了所有能关闭的`line_number`和`highlight` 都不行

**Comment by zjy01** [comment]
@tetsaicn @LarryLeo 
当我在 ```[代码格式] ``` 中，把代码格式写上的时候，这个问题解决了。

**Comment by tetsaicn** [comment]
@LarryLeo 
```
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:
```

**Comment by zBorwen** [comment]
这个问题没得解决嘛 我也碰到了

**Comment by zBorwen** [comment]
@tetsaicn  关闭的都关了还是不行 请问你的弄好了吗

**Comment by tetsaicn** [comment]
好了，忘记怎么弄了。。。

记得把自带highlight全部关掉，就好了


在 2018年02月10日 19:54, zBorwen 写道:

**Comment by cyang812** [comment]
为什么我的也是这样？使用 github-v2 有三个行号

**Comment by nameNotNull** [comment]
有人解决了吗，跪求

**Comment by tetsaicn** [comment]
@nameNotNull 已经解决了，我的解决办法是删除原来主题所有的高亮相关组件，自己导入，主题里的高亮就是在互相干扰，压根没用......

**Comment by lyh543** [comment]
@nameNotNull @zBorwen 关闭以后`hexo g`之前还需要`hexo clean`

站点配置文件`\_config.yml`
```yml
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:
```

**Comment by KnightKilito** [comment]
@lyh543 

> @nameNotNull @zBorwen 关闭以后`hexo g`之前还需要`hexo clean`
> 
> 站点配置文件`\_config.yml`
> 
> ```yaml
> highlight:
>   enable: false
>   line_number: false
>   auto_detect: false
>   tab_replace:
> ```

我这样了也还是不行……
站点配置文件：
```yml
highlight:
  enable: false
  line_number: false # true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: false # true
  line_number: false # true
  tab_replace: ''
```

主题配置文件：
```yml
prettify:
    enable: true
    theme: "vibrant-ink" # "github-v2" (此处是为了方便展示错误情况换成vibrant-ink，即使是github-v2也一样)
hanabi:
    enable: false
    line_number: false # true
    includeDefaultColors: false # true
    customColors:
```
文档说两者用其一，我就只用了prettify，按照上面那样配置，也hexo clean跟hexo g了，还是会出现行号出现3次的情况……而且比如说10它不是显示成
“10”
而是
“1
0”这样……
