### ISSUE TITLE
custom defined page is error?

### ISSUE THREAD

**Issue by labike** [viosey/hexo-theme-material#680]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

I'm follow doc change '_config.yml', and add 'tags' 'about' but get the pages is this:

```
pages:
        关于我:
            link: "/about"
            icon: person
            divider: false
        标签云:
            link: '/tags'
            icon: tag
            divider: false
```
![tags](http://oo8hp4ueg.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-07-13%20%E4%B8%8A%E5%8D%8811.58.59.png)
