### ISSUE TITLE
侧边栏显示不正确

### ISSUE THREAD

**Issue by zjt2005** [viosey/hexo-theme-material#728]
## 反馈

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

我并且确定好像除了我一个人网上并无此BUG 因为我根本没有查到。
----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

### 使用Paradox时
侧边栏显示不正确，点击侧边栏按钮不弹出侧边栏，必须翻到底部才有（Hexo s显示正确，提交到GithubPage显示不正确)

###使用Isolation时
文章无法显示(不管是本地还是GitpAges都不正确)

### 我的尝试
* 重新HexoInit并去掉所有不必要插件重试  ----不行
* 重新安装主题    -----不行
* 把两个config全部恢复默认 ----不行
* 反复HexoClean  -----不行
* 把博客评论系统从来比例改成Gitalk   -----好了

什么鬼

**Comment by zjt2005** [comment]
# 一些数据

## 主题文件配置
```yml
# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/favicon.png"
    high_res_favicon: "/img/favicon."
    apple_touch_icon: "/img/apple-touch.png"
    keywords: LittleBlack,小黑,小黑的博客
    site_verification:
        google:
        baidu: 

    # Enable generate structured-data as JSON+LD for SEO or not.
    #    Set as 'false' if it cause some wrong when `hexo g`.
    structured_data: true

# Jump Links Settings
url:
    rss: atom.xml
    daily_pic: "#"
    logo: "#"


# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
scheme: Paradox
#scheme: Isolation

# UI & UX: slogan, color, effect
uiux:
    slogan: "What? How? Why?"
    theme_color: "#0097A7"
    theme_sub_color: "#00838F"
    hyperlink_color: "#00838F"
    button_color: "#757575"
    android_chrome_color: "#0097A7"
    nprogress_color: "#29d"
    nprogress_buffer: "800"

# JS Effect Switches
js_effect:
    fade: false
    smoothscroll: false

# Reading experience
reading:
    entry_excerpt: 80

# Thumbnail Settings
thumbnail:
    purecolor:
    random_amount: 19

# Background Settings
# bing available parameter:
#    new | color= | type=
#        color available value: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow
#        type available value: A (animal), C (culture), N (nature), S (space), T (travel)
background:
    purecolor: "#F5F5F5"
    #bgimg: "/img/bg.png"
    bing:
        enable: false
        parameter:

# Images Settings
img:
    logo: "/img/logo.png"
    avatar: "/img/avatar.png"
    daily_pic: "/img/daily_pic.png"
    sidebar_header: "/img/sidebar_header.png"
    random_thumbnail: "/img/random/material-"
    footer_image:
        #upyun_logo:
            #link: "https://www.upyun.com/"
            #src: "/img/upyun_logo.svg"

# Custom Fonts
#    family: the font-family which will be used in the theme
#    use: uri of fonts host.
#        Available value: google | baomitu | ustc | custom | catnet
#        - When you set as 'custom', you should fill in the value of 'custom_font_host', which should be a mirror of google fonts.
#        - If you have setup your custom font-family, don't forget to add style tag with @font-face or link.tag with font css
#          to /source/data/head.yml as custom code, to load custom font files.
fonts:
    family: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif
    use: google
    custom_font_host:

# Card Elevation Level
card_elevation: 2

# Copyright
# Specify the date when the site was setup.
#    For example, if you set it as 2015, then footer will show '© 2015 - 2017'
copyright_since: 2018

# Footer Text
# You can specify the text you want to show in footer, HTML tag is supported.
#   For example, you can setup ICP license number as:
#       '<a href="http://www.miitbeian.gov.cn" rel="nofollow">某ICP备xxxxxxxx号-x</a>'
footer_text: HelloWorld!

# Qrcode for redirect at other device
#    use: choose which method to generate the qrcode for each posts.
#        Available value: plugin | online
#            - When use "plugin", you need to install the hexo-helper-qrcode.
#            - When use "online", the qrcode will be generated by 'pan.baidu.com' in China.
qrcode:
    enable: true
    use: plugin

# Code highlight
# You can only enable one of them to avoid issues.
# Also you need to disable highlight option in hexo's _config.yml.
#
#    Prettify
#        theme: # Available value in /source/css/prettify/[theme].min.css
prettify:
    enable: true
    theme: "github-v2"

#    Hanabi (https://github.com/egoist/hanabi)
#        line_number: [true/false] # Show line number for code block
#        includeDefaultColors: [true/false] # Use default hanabi colors
#        customColors: This value accept a string or am array to setting for hanabi colors.
#                    - If `includeDefaultColors` is true, this will append colors to the color pool
#                    - If `includeDefaultColors` is false, this will instead default color pool
hanabi:
    enable: false
    line_number: true
    includeDefaultColors: true
    customColors:

# Post License
# You can specify the text you want to show in the end of your posts and pages, HTML tag is supported.
#   For example, you can setup a CC license as:
#       'This blog is under a <a href="/creativecommons.html" target="_blank">CC BY-NC-SA 3.0 Unported License</a>'
# You can also use Front-Matter `license` to override this setting.
license: This blog is under a <a href="/creativecommons.html" target="_blank">CC BY-NC-SA 3.0 Unported License</a>

# Gallery Panel
# You must activate Formspree before using
gallery:
    panel_show: false
    left_show: true
    left_title: Introduction
    left_info: This is a Example.
    right_show: true
    right_title: Get in touch

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# TOC Button

toc:
#   use: choose whether the line_number of toc will show or not.
#       Available value of "linenumber": true | false
    linenumber: true

# SNS Menu
sns:
    email: "littleblack@i2pmail.org"
    facebook: 
    twitter: 
    googleplus: 
    weibo:
    instagram:
    tumblr:
    github: "https://github.com/zjt2005/"
    linkedin:
    zhihu:
    bilibili:
    telegram:
    v2ex:
    segmentfault:

# SNS Share Switch
sns_share:
    twitter: true
    facebook: true
    googleplus: true
    weibo: true
    linkedin: true
    qq: true
    telegram: false

# Sidebar Customize
#Matreial icon :https://material.io/tools/icons
sidebar:
    dropdown:
        Email Me:
            link: "mailto:littleblack@i2pmail.org"
            icon: email
        RSS Feed:
            link: "atom.xml"
            icon: rss_feed
    homepage:
        use: true
        icon: home
        divider: false
    archives:
        use: true
        icon: inbox
        divider: false
    categories:
        use: true
        icon: chrome_reader_mode
        divider: false
    pages:
        标签云:
            link: "/tags"
            icon: cloud
            divider: false
        #映像:
            #link: "/gallery"
            #icon: images
            #divider: false
        关于:
            link: "/about"
            icon: person
            divider: false
        时间轴:
            link: "/timeline"
            icon: timeline
            divider: false
        友链:
            link: "/links"
            icon: insert_link
            divider: false
        梯子:
            link: "/GFW/index.html"
            icon: language
            divider: false
    article_num:
        use: true
        divider: false
    footer:
        divider: false
        theme: true
        support: false
        feedback: false
        material: true


# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------

# Comment Systems
# Available value of "use":
#     disqus | disqus_click | changyan | livere | gitment | gitalk | valine | wildfire
# If you want to use gitment or gitalk,you should get the client_id and client_secret from https://github.com/settings/applications/new
# If you want to use valine,you should get the app_id and app_key from https://leancloud.cn ,more setting please see https://valine.js.org
comment:
    use: gitalk
    shortname: # duoshuo or disqus shortname
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    livere_data_uid:
    gitment_repo: 
    gitment_owner:  
    gitment_client_id: 
    gitment_client_secret : 
    valine_leancloud_appId:  # leancloud application app id
    valine_leancloud_appKey:  # leancloud application app key
    valine_notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
    valine_verify: false # valine verify code (true/false)
    valine_pageSize: 10 # comment list page size
    valine_avatar: identicon # gravatar style https://valine.js.org/#/avatar
    valine_lang: zh-cn # i18n
    valine_placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
    valine_guest_info: nick,mail,link #valine comment header info
    gitalk_repo: zjt2005.github.io
    gitalk_owner: zjt2005
    gitalk_client_id: fa*************8836
    gitalk_client_secret: 66*******************************800e7
    wildfire_database_provider: firebase # firebase or wilddog
    wildfire_wilddog_site_id:
    wildfire_firebase_api_key:
    wildfire_firebase_auth_domain:
    wildfire_firebase_database_url:
    wildfire_firebase_project_id:
    wildfire_firebase_storage_bucket:
    wildfire_firebase_messaging_sender_id:
    wildfire_theme: light # light or dark
    wildfire_locale: en # en or zh-CN


# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: local
    swiftype_key: Z*******************uTR

# Analytics Systems
# Available value:
#     baidu | google | cnzz
analytics:
    google_site_id: UA-708****9-1
    baidu_site_id: 53a322cf0***********1604e758
    cnzz_site_id:

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"

# Files Vendors
# Set a CDN for the files src you want to customize. The url should with protocol.
# Default(empty) will load the files from the origin server.
vendors:
# MaterialCDN
#   You can load theme unique files from your private cdn or oss.
#   The new src will have the base domain you configured below.
#   For example
#       materialcdn: https://cdn.jsdelivr.net/npm/hexo-material@1.4.0/source
    materialcdn:

# Third party library
#   You can load these files from public cdn.
#   For example
#       jquery: https://cdn.bootcss.com/jquery/2.2.1/jquery.js
    # jQuery 2.2.0
    jquery:
    # nprogress 0.2.0
    nprogress:
    # FontAwesome 4.5.0
    fontawesome:
    # MathJax 2.7.0-2.7.1
    mathjax:
    # Prettify r298 (only prettify.js)
    prettify:
    # Material Icons 3.0.1
    material_icons:

```


## 博客总的Config.yml配置
```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: LittleBlack's Blog
subtitle: What? How? Why?
description: This is LittleBlack's Blog.
author: LittleBlack
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: www.hackblack.cn/ #这里如果你只部署了一个平台，那么填那个平台的地址，或者/都行，如果你部署在了两个平台上，那么就只写/吧
root: /
permalink: posts/:abbrlink/
#permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - CNAME
  - robots.txt
  - GFW/**

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: categories
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
feed:
  type: atom
  path: atom.xml
  limit: 20

#plugins:
abbrlink:
  alg: crc16  #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex

encrypt:
    enable: true

search:
    path: search.xml
    field: all

baidusitemap:
path: baidusitemap.xml

baidu_url_submit:
  count: 30 ## 比如3，代表提交最新的三个链接
  host: www.hackblack.cn
  token: lLtibzz*********M
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里

shareto: true

#index_generator:
#  per_page: 10
#  order_by: -date



## Themes: https://hexo.io/themes/
theme: hexo-theme-material
#theme: blackshow

# Deployment

deploy:
- type: git
  repo: 
    github: https://github.com/zjt2005/zjt2005.github.io.git
    coding: https://git.dev.tencent.com/Hackblack/hackblack.git
  branch: master
  message: Upd blog.
- type: baidu_url_submitter

# Make Website Faster
service_worker:
  maximumFileSizeToCacheInBytes: 5242880
  staticFileGlobs:
  - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: true

filter_optimize:
  enable: true
  # remove static resource query string
  #   - like `?v=1.0.0`
  remove_query_string: true
  # remove the surrounding comments in each of the bundled files
  remove_comments: true
  css:
    enable: false
    # bundle loaded css file into the one
    bundle: true
    # use a script block to load css elements dynamically
    delivery: true
    # make specific css content inline into the html page
    #   - only support the full path
    #   - default is ['css/main.css']
    inlines:
    excludes:
  js:
    # bundle loaded js file into the one
    bundle: true
    excludes:
  # set the priority of this plugin,
  # lower means it will be executed first, default is 10
  priority: 12
```

## Package.json
```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "acorn": "^6.1.1",
    "core-js": "^3.1.4",
    "eslint": "^6.0.1",
    "hexo": "^3.9.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-asset-image": "0.0.3",
    "hexo-baidu-url-submit": "0.0.6",
    "hexo-blog-encrypt": "^2.2.1",
    "hexo-clean-css": "0.0.3",
    "hexo-deployer-git": "^1.0.0",
    "hexo-filter-optimize": "^0.2.5",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-qrcode": "^1.0.2",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.2.11",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.2.2",
    "hexo-service-worker": "^1.0.1",
    "hexo-tag-bootstrap": "^0.1.2",
    "request": "^2.88.0"
  }
}

```
Mayday!!
